export enum EItemTags {
  // Brazilian Food
  BRAZILIAN = 'BRAZILIAN',
  NORTHEASTERN = 'NORTHEASTERN',
  MINAS_GERAIS = 'MINAS_GERAIS',
  SOUTHERN = 'SOUTHERN',
  BAHIAN = 'BAHIAN',
  RIO_DE_JANEIRO = 'RIO_DE_JANEIRO',
  SAO_PAULO = 'SAO_PAULO',
  AMAZONIAN = 'AMAZONIAN',

  // Fast Food
  HAMBURGER = 'HAMBURGER',
  PIZZA = 'PIZZA',
  SANDWICH = 'SANDWICH',
  HOT_DOG = 'HOT_DOG',
  FRENCH_FRIES = 'FRENCH_FRIES',

  // International Food
  ITALIAN = 'ITALIAN',
  JAPANESE = 'JAPANESE',
  CHINESE = 'CHINESE',
  MEXICAN = 'MEXICAN',
  INDIAN = 'INDIAN',
  THAI = 'THAI',
  KOREAN = 'KOREAN',
  FRENCH = 'FRENCH',
  SPANISH = 'SPANISH',
  GREEK = 'GREEK',
  TURKISH = 'TURKISH',
  LEBANESE = 'LEBANESE',
  ARGENTINIAN = 'ARGENTINIAN',
  PERUVIAN = 'PERUVIAN',
  AMERICAN = 'AMERICAN',

  // Asian
  ASIAN = 'ASIAN',
  SUSHI = 'SUSHI',
  YAKISOBA = 'YAKISOBA',
  TEMAKI = 'TEMAKI',
  RAMEN = 'RAMEN',

  // Pasta
  PASTA = 'PASTA',
  LASAGNA = 'LASAGNA',
  SPAGHETTI = 'SPAGHETTI',
  GNOCCHI = 'GNOCCHI',
  RISOTTO = 'RISOTTO',

  // Meat
  BARBECUE = 'BARBECUE',
  CHICKEN = 'CHICKEN',
  BEEF = 'BEEF',
  PORK = 'PORK',
  RIBS = 'RIBS',
  STEAK = 'STEAK',

  // Seafood
  SEAFOOD = 'SEAFOOD',
  FISH = 'FISH',
  SHRIMP = 'SHRIMP',
  SALMON = 'SALMON',

  // Vegetarian/Vegan
  VEGETARIAN = 'VEGETARIAN',
  VEGAN = 'VEGAN',
  SALAD = 'SALAD',
  NATURAL = 'NATURAL',

  // Beverages
  BEVERAGES = 'BEVERAGES',
  JUICES = 'JUICES',
  SOFT_DRINKS = 'SOFT_DRINKS',
  BEER = 'BEER',
  WINE = 'WINE',
  WATER = 'WATER',
  ENERGY_DRINKS = 'ENERGY_DRINKS',
  COFFEE = 'COFFEE',
  TEA = 'TEA',

  // Desserts & Sweets
  DESSERTS = 'DESSERTS',
  SWEETS = 'SWEETS',
  ICE_CREAM = 'ICE_CREAM',
  ACAI = 'ACAI',
  CAKES = 'CAKES',
  PIES = 'PIES',
  CHOCOLATES = 'CHOCOLATES',
  BRIGADEIROS = 'BRIGADEIROS',

  // Snacks & Appetizers
  SNACKS = 'SNACKS',
  APPETIZERS = 'APPETIZERS',
  PASTEL = 'PASTEL',
  COXINHA = 'COXINHA',
  ESFIHA = 'ESFIHA',
  EMPADA = 'EMPADA',
  TAPIOCA = 'TAPIOCA',
  CREPE = 'CREPE',

  // Bakery & Confectionery
  BAKERY = 'BAKERY',
  BREAD = 'BREAD',
  HOMEMADE_SWEETS = 'HOMEMADE_SWEETS',
  SAVORY_SNACKS = 'SAVORY_SNACKS',

  // Special Categories
  LUNCH_BOX = 'LUNCH_BOX',
  EXECUTIVE = 'EXECUTIVE',
  SELF_SERVICE = 'SELF_SERVICE',
  BUFFET = 'BUFFET',
  ALL_YOU_CAN_EAT = 'ALL_YOU_CAN_EAT',

  // Dietary
  GLUTEN_FREE = 'GLUTEN_FREE',
  LACTOSE_FREE = 'LACTOSE_FREE',
  LIGHT = 'LIGHT',
  FITNESS = 'FITNESS',
  DIET = 'DIET',

  // Meal Times
  BREAKFAST = 'BREAKFAST',
  BRUNCH = 'BRUNCH',
  LUNCH = 'LUNCH',
  DINNER = 'DINNER',
  AFTERNOON_SNACK = 'AFTERNOON_SNACK',
  LATE_NIGHT = 'LATE_NIGHT',

  // Special Occasions
  PARTY = 'PARTY',
  BIRTHDAY = 'BIRTHDAY',
  CORPORATE = 'CORPORATE',
  FAMILY = 'FAMILY',

  // Other Services
  FROZEN = 'FROZEN',
  GROCERY = 'GROCERY',
  PHARMACY = 'PHARMACY',
  PET_SHOP = 'PET_SHOP',
  CONVENIENCE = 'CONVENIENCE',
}
